version: "3.9"


services:
  database: 
    build: ./database
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - spring_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  backend:
    build: ./backend
    container_name: backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    networks:
      - spring_net
    depends_on:
      database:
        condition: service_healthy
  
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - frontend_net

           
networks:
  spring_net:
  frontend_net: